export let Request: import("axios").AxiosInstance;
export let setToken: (token: string) => void;
export let setURL: (url: string) => void;
export let APIError: (error: string) => string;
export let Account: typeof import("./account/account");
export let AccountTokens: typeof import("./account/tokens");
export let AccountSecurity: typeof import("./account/security");
export let AccountIntegrations: typeof import("./account/integrations");
export let AccountTwoFactor: typeof import("./account/twoFactor");
export let Workspace: typeof import("./workspaces/workspaces");
export let WorkspacePayments: typeof import("./workspaces/payments");
export let WorkspaceInvoices: typeof import("./workspaces/invoices");
export let WorkspaceUsage: typeof import("./workspaces/usage");
export let WorkspaceSubscription: typeof import("./workspaces/subscription");
export let WorkspaceMembers: typeof import("./workspaces/members");
export let WorkspaceRegistries: typeof import("./workspaces/registries");
export let Projects: typeof import("./projects/projects");
export let ProjectDomains: typeof import("./projects/domains");
export let ProjectSecrets: typeof import("./projects/secrets");
export let ProjectServices: typeof import("./projects/services");
export let Deployments: typeof import("./deployments/deployments");
export let DeploymentLogs: typeof import("./deployments/logs");
export let DeploymentInstances: typeof import("./deployments/instances");
export let Utils: typeof import("./utils/utils");
//# sourceMappingURL=index.d.ts.map