module.exports = {
    // SDK
    Request: require('./request').request,
    setToken: require("./request").setToken,
    setURL: require("./request").setURL,
    APIError: require("./request").APIError,
    // Account
    Account: require("./account/account"),
    Invoices: require("./account/invoices"),
    Payments: require("./account/payments"),
    Tokens: require("./account/tokens"),
    Events: require("./account/events"),
    Logins: require("./account/logins"),
    Integrations: require("./account/integrations"),
    TwoFactor: require("./account/twoFactor"),
    Sessions: require("./account/sessions"),
    UserWorkspace: require("./account/workspace"),
    // Projects
    Projects: require("./projects/projects"),
    ProjectEvents: require("./projects/events"),
    ProjectMembers: require("./projects/members"),
    ProjectEnvironments: require("./projects/environments"),
    // Services
    Services: require("./services/services"),
    ServiceInfo: require("./services/info"),
    ServiceDomains: require("./services/domains"),
    ServiceVariables: require("./services/variables"),
    // Deployments
    Deployments: require("./deployments/deployments"),
    DeploymentLogs: require("./deployments/logs"),
    DeploymentActions: require("./deployments/actions"),
    // Support
    Support: require("./support/support"),
    // Utils
    Utils: require("./utils/utils")
}