module.exports = {
  // SDK
  Request: require('./request').request,
  setToken: require('./request').setToken,
  setURL: require('./request').setURL,
  APIError: require('./request').APIError,
  // Account
  Account: require('./account/account'),
  AccountTokens: require('./account/tokens'),
  AccountSecurity: require('./account/security'),
  AccountIntegrations: require('./account/integrations'),
  AccountTwoFactor: require('./account/twoFactor'),
  AccountWorkspaces: require('./account/workspace'),
  // Workspaces
  Workspace: require('./workspaces/workspaces'),
  WorkspacePayments: require('./workspaces/payments'),
  WorkspaceInvoices: require('./workspaces/invoices'),
  WorkspaceUsage: require('./workspaces/usage'),
  WorkspaceSubscription: require('./workspaces/subscription'),
  WorkspaceMembers: require('./workspaces/members'),
  WorkspaceRegistries: require('./workspaces/registries'),
  // Projects
  Projects: require('./projects/projects'),
  ProjectDomains: require('./projects/domains'),
  ProjectSecrets: require('./projects/secrets'),
  ProjectServices: require('./projects/services'),
  // Deployments
  Deployments: require('./deployments/deployments'),
  DeploymentLogs: require('./deployments/logs'),
  DeploymentInstances: require('./deployments/instances'),
  // Utils
  Utils: require('./utils/utils')
}
