module.exports = {
    // SDK
    Request: require('./request').request,
    setToken: require("./request").setToken,
    setURL: require("./request").setURL,
    APIError: require("./request").APIError,
    // Account
    Account: require("./account/account"),
    Tokens: require("./account/tokens"),
    Logins: require("./account/logins"),
    Integrations: require("./account/integrations"),
    TwoFactor: require("./account/twoFactor"),
    Sessions: require("./account/sessions"),
    UserWorkspace: require("./account/workspace"),
    // Workspaces
    Workspace: require("./workspaces/workspaces"),
    WorkspacePayments: require("./workspaces/payments"),
    WorkspaceInvoices: require("./workspaces/invoices"),
    WorkspaceUsage: require("./workspaces/usage"),
    WorkspaceSubscription: require("./workspaces/subscription"),
    // Projects
    Projects: require("./projects/projects"),
    ProjectEvents: require("./projects/events"),
    ProjectMembers: require("./projects/members"),
    ProjectEnvironments: require("./projects/environments"),
    ProjectBuilds: require("./projects/builds"),
    // Deployments
    Deployments: require("./deployments/deployments"),
    DeploymentLogs: require("./deployments/logs"),
    DeploymentActions: require("./deployments/actions"),
    // Support
    Support: require("./support/support"),
    // Utils
    Utils: require("./utils/utils")
}